### ISSUE TITLE
error while compilation on Manjaro

### ISSUE THREAD

**Issue by egodasa** [turionpowercontrol/tpc#40]
![tpc](https://user-images.githubusercontent.com/9961837/29747530-0a5a41d6-8b0f-11e7-8ce2-1ee8dc4b31ff.jpg)
I found that tpc available as a "bin" file for ubuntu, but not with Manjaro. So, I compile it manually and i got this error. Previously, I'm using Archlinux and everything ok. But on Manjaro i see that error.
Thx :)

**Comment by egodasa** [comment]
Problem fixed. I'm using another version on gcc and now it works.

**Comment by ArnouldN** [comment]
I have still the same bug in Ubuntu 20.04 and Linux Mint Debian Edition. So issue was closed but not corrected...

It is because function round() is defined twice, in the libraries of gcc and again in the source code of TurionPowerControl. If the funtion's name is modified in the files MSVC_Round.h and MSVC_Round.cpp to eg round_mod() then compilation is OK. TurionPowerControl then uses the standard round() function of gcc but works very well.
